# Generated by Django 3.1.1 on 2020-09-22 07:16

import ckeditor.fields
import django_2gis_maps.fields
import django_2gis_maps.mixins
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("trips", "0002_markerttttt"),
    ]

    operations = [
        migrations.CreateModel(
            name="Countries",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField(blank=True, max_length=20, null=True)),
                ("content", ckeditor.fields.RichTextField(blank=True, null=True)),
            ],
            options={
                "verbose_name_plural": "Content",
            },
        ),
        migrations.CreateModel(
            name="Points",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("address", django_2gis_maps.fields.AddressField(max_length=100)),
                ("geolocation", django_2gis_maps.fields.GeoLocationField()),
            ],
            options={
                "verbose_name_plural": "Points",
            },
            bases=(django_2gis_maps.mixins.DoubleGisMixin, models.Model),
        ),
        migrations.DeleteModel(
            name="Markerttttt",
        ),
        migrations.AddField(
            model_name="countries",
            name="markermap",
            field=models.ManyToManyField(to="trips.Points"),
        ),
    ]
