# Generated by Django 3.1.1 on 2020-09-22 07:24

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("trips", "0005_remove_countries_markermap"),
    ]

    operations = [
        migrations.AddField(
            model_name="countries",
            name="marker_map",
            field=models.ManyToManyField(to="trips.Points"),
        ),
    ]
