service: taranova-travel-dev
provider:
  name: aws
  runtime: python3.7
  timeout: 60
  versionFunctions: false
  endpointType: REGIONAL
  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - 's3:ListBucket'
      Resource:
        - 'arn:aws:lambda:us-east-1:080515567996:function:Travel'
'
    - Effect: 'Allow'
      Action:
        - 's3:PutObject'
      Resource:
        - 'arn:aws:lambda:us-east-1:080515567996:function:Travel'
'
functions:
  resizer:
    environment:
      PYTHONPATH: src
    handler: resizer.lambda_function.lambda_handler
    events:
      - s3:
          bucket: taranova-travel
          event: s3:ObjectCreated:*
          existing: true
plugins:
  - serverless-python-requirements
custom:
  pythonRequirements:
    dockerizePip: non-linux