# Generated by Django 3.0.5 on 2020-04-17 17:32

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TripInfo",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("country", models.TextField(unique=True)),
                ("descr", models.TextField(blank=True, null=True)),
                ("number", models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
