# Generated by Django 3.0.8 on 2020-07-31 16:49

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Skyscanner",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name_city", models.CharField(max_length=2)),
            ],
            options={"verbose_name_plural": "cities",},
        ),
    ]
