# Generated by Django 3.0.8 on 2020-07-31 17:06

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("preparation", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="skyscanner",
            name="name_city",
            field=models.CharField(max_length=30),
        ),
    ]
