# Generated by Django 3.0.8 on 2020-09-08 18:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Trips",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True, default="", max_length=100, unique=True
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=50)),
                ("user_location", models.CharField(blank=True, max_length=100)),
                ("destination", models.CharField(blank=True, max_length=100)),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                ("budget", models.IntegerField(default=0)),
                ("participants_total", models.IntegerField(default=1)),
                ("comments_total", models.IntegerField(default=0)),
                ("public", models.BooleanField(default=False)),
                ("pins_total", models.IntegerField(default=0)),
                ("packing_list", models.TextField(blank=True, max_length=2000)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "trip",
                "verbose_name_plural": "trips",
            },
        ),
    ]
