# Generated by Django 3.1.1 on 2020-09-20 07:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0002_comments"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="trips",
            name="pins_total",
        ),
        migrations.RemoveField(
            model_name="trips",
            name="public",
        ),
    ]
