# Generated by Django 3.1.1 on 2020-09-20 07:24

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0003_auto_20200920_0722"),
    ]

    operations = [
        migrations.AddField(
            model_name="trips",
            name="public",
            field=models.BooleanField(default=False),
        ),
    ]
