# Generated by Django 3.1.1 on 2020-09-21 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_trips_public'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comments',
        ),
    ]
