# Generated by Django 3.1.1 on 2020-09-22 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0005_delete_comments"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="trips",
            options={
                "verbose_name": "trip",
                "verbose_name_plural": "Запланированные путешествия",
            },
        ),
    ]
