# Generated by Django 3.0.8 on 2020-09-05 11:15

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0003_remove_photo_thumbnail"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="precontent",
            field=models.TextField(blank=True, null=True),
        ),
    ]
