# Generated by Django 3.1.1 on 2020-09-22 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0006_random"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="comment",
            options={"verbose_name_plural": "Комментарии"},
        ),
        migrations.AlterModelOptions(
            name="photo",
            options={"verbose_name_plural": "Фотографии"},
        ),
        migrations.AlterModelOptions(
            name="post",
            options={"verbose_name_plural": "Посты"},
        ),
        migrations.AlterModelOptions(
            name="random",
            options={"verbose_name_plural": "Фотографии на главную страницу"},
        ),
    ]
