# Generated by Django 3.1.1 on 2020-09-21 23:26

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("contacts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shop",
            name="location",
            field=django.contrib.gis.db.models.fields.PointField(
                default=(0.0, 0.0, 0.0), geography=True, srid=4326
            ),
        ),
    ]
