# Generated by Django 3.0.5 on 2020-04-27 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("vietnam", "0003_auto_20200427_1352"),
    ]

    operations = [
        migrations.RenameField(
            model_name="viedays", old_name="predecription", new_name="predescription",
        ),
    ]
