# Generated by Django 3.0.5 on 2020-04-30 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("vietnam", "0004_auto_20200427_1729"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="viedays",
            options={"verbose_name_plural": "Information about Vietnam"},
        ),
    ]
